spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rental_management_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: peter
    password: peter

  jpa:
    hibernate:
      ddl-auto: update  # Dev only â€” auto create/update tables
    show-sql: true

logging:
  level:
    root: INFO
    com.peterscode: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8081

jwt:
  secret: b61eb47178bc3fc9fedd50fecb3f12416e0cc2fe3c37df6a809c2d7f33a060fb5398cab8d664a88c88fca90c8e5d9c6ce41e42e14e9919b980975b8dd4c56a5e
  expiration: 86400000
